### PR TITLE
Feature/#46 icons

### PR DESCRIPTION
**Pull request by GewoonMaarten**
closes #158

### CODE REVIEW

**Review by DanielvanVliet — CHANGES_REQUESTED** [review]
In storybook, the single icon story does not show any icon.
The show code does not seem correct either for single icon.

**Comment by GewoonMaarten** [comment]
> In storybook, the single icon story does not show any icon.
> The show code does not seem correct either for single icon.

I've updated the `show code` block

**Comment by DanielvanVliet** [comment]
I think it would be nice if we update IconButton to use our own icons

**Comment by GewoonMaarten** [comment]
> I think it would be nice if we update IconButton to use our own icons

I've updated all stories that use material-ui/icons and replaced them with our own icons. I've added @gemeente-denhaag/icons as devDependencies. Something I would like to do with all other packages. I think this is much neater than relative imports.

**Review by DanielvanVliet — APPROVED** [review]

**Comment by DanielvanVliet** [comment]
I don't think we need `@material-ui/icons` anymore, can you remove it?

**Review by joostvanviegen — APPROVED** [review]

**Pull request merged**
